# Rigidty Examples

In this notebook, we will be exploring the rigidity.py module


In [1]:
from math import sin, cos, pi
import numpy as np
import rigidity

## Four vertex example

In [2]:
# Define translations for the affine transformation
l1 = np.matrix([0,0,3]).transpose()
l2 = np.matrix([0,0,10]).transpose()

# Define the rotations for the affine transformations
theta1 = pi/6
theta2 = pi/20

S1 = np.matrix([
    [cos(theta1), -sin(theta1), 0],
    [sin(theta1), cos(theta1), 0],
    [0, 0, 1]])

S2 = np.matrix([
    [cos(theta2), -sin(theta2), 0],
    [sin(theta2), cos(theta2), 0],
    [0, 0, 1]])

T1 = rigidity.AffineTransform(S1, l1)
T2 = rigidity.AffineTransform(S2, l2)

# Define the vertices and edge markings for the graph
verts = [0, 1, 2, 3]
edges = {
    0: [(1, 0, 0), (2, 0, 0), (3, 0, 0)],
    1: [(0, 1, 0), (2, 1, 0), (3, 0, 0)],
    2: [(0, 0, 1), (1, 0, 1), (3, 0, 0)],
    3: [(0, 1, 1), (1, 0, 1), (2, 1, 0)]
}
G = [verts, edges]

# Define the 'base' framework
r1 = np.matrix([2, 0, 0]).transpose()
r2 = np.matrix([3, 2, 1]).transpose()
r3 = np.matrix([4, 0, 2]).transpose()
r4 = np.matrix([5, 2, 3]).transpose()
P = [r1, r2, r3, r4]

# Define the number of group elements to create
n = (24, 2)

# Create the framework
f1 = rigidity.ScrewFramework(G, P, T1, T2)


In [3]:
# Create the rigidity matrix
R = f1.rigidityMatrix()
np.linalg.matrix_rank(R)

10

## One vertex example

In [4]:
verts = [0]
edges = {0: [(0, 0, 1), (0, 1, 0), (0, 1, 1)]}
G = [verts, edges]

r1 = np.matrix([1, 0, 0]).transpose()
P = [r1]

n = (24, 2)
f2 = rigidity.ScrewFramework(G, P, T1, T2)

In [5]:
from sympy import Matrix
R2 = f2.rigidityMatrix()

In [6]:
import scipy.linalg
scipy.linalg.null_space(R2)

array([[2.3995217e-16, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00]])

## Clasical Framework in 3D

In [7]:
verts = [0,1,2,3]
edges = {
    0: [1, 2],
    1: [0, 2, 3],
    2: [0, 1, 3],
    3: [1, 2]
}
G = [verts, edges]

r1 = np.matrix([0, 0, 0]).transpose()
r2 = np.matrix([1, 0, 0]).transpose()
r3 = np.matrix([0, 1, 0]).transpose()
r4 = np.matrix([0, 0, 1]).transpose()
P = [r1, r2, r3, r4]

f3 = rigidity.Framework(G, P)

In [8]:
f3.rigidityMatrix()

array([[-1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -1.,  0., -1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0., -1.,  0.,  0.,  0., -1.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  0., -1.,  1.]])

In [9]:
f3.symbolicRigidityMatrix()

Matrix([
[p0 - p1, -p0 + p1,        0,        0],
[p0 - p2,        0, -p0 + p2,        0],
[      0,  p1 - p2, -p1 + p2,        0],
[      0,  p1 - p3,        0, -p1 + p3],
[      0,        0,  p2 - p3, -p2 + p3]])

In [10]:
np.linalg.matrix_rank(f3.rigidityMatrix())

5

In [11]:
f3.infinitesimalFlex()

[Matrix([
 [0],
 [0],
 [0]]),
 Matrix([
 [         0],
 [         0],
 [-x30 + x32]]),
 Matrix([
 [0],
 [0],
 [0]]),
 Matrix([
 [x30],
 [x32],
 [x32]])]

In [12]:
%matplotlib widget
f3.draw()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## Classical Framework in 2D

In [13]:
verts = [0,1,2,3]
edges = {
    0: [1, 2],
    1: [0, 2, 3],
    2: [0, 1, 3],
    3: [1, 2]
}
G = [verts, edges]

r1 = np.matrix([0, 0]).transpose()
r2 = np.matrix([1, 0]).transpose()
r3 = np.matrix([0, 1]).transpose()
r4 = np.matrix([1, 1]).transpose()
P = [r1, r2, r3, r4]

f4 = rigidity.Framework(G, P)

In [14]:
f4.rigidityMatrix()

array([[-1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -1., -1.,  1.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0., -1.,  0.,  1.,  0.]])

In [15]:
f4.symbolicRigidityMatrix()

Matrix([
[p0 - p1, -p0 + p1,        0,        0],
[p0 - p2,        0, -p0 + p2,        0],
[      0,  p1 - p2, -p1 + p2,        0],
[      0,  p1 - p3,        0, -p1 + p3],
[      0,        0,  p2 - p3, -p2 + p3]])

In [16]:
f4.infinitesimalFlex()

[Matrix([
 [0],
 [0]]),
 Matrix([
 [0],
 [0]]),
 Matrix([
 [0],
 [0]]),
 Matrix([
 [0],
 [0]])]

In [18]:
f4.draw()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …