# Rigidty Examples

In this notebook, we will be exploring the rigidity.py module


In [2]:
import sys
sys.path.append('..')
from math import sin, cos, pi
import numpy as np
import rigidity

In [61]:
import importlib
importlib.reload(rigidity)

<module 'rigidity' from 'c:\\Users\\josep\\OneDrive - University of St Andrews\\Documents\\St Andrews\\Laidlaw\\GitHub\\laidlaw-origami\\rigidity\\examples\\..\\rigidity.py'>

## Four vertex example

In [55]:
# Define translations for the affine transformation
l1 = np.array([0,0,3])
l2 = np.array([0,0,10])

# Define the rotations for the affine transformations
theta1 = pi/6
theta2 = pi/20

S1 = np.array([
    [cos(theta1), -sin(theta1), 0],
    [sin(theta1), cos(theta1), 0],
    [0, 0, 1]])

S2 = np.array([
    [cos(theta2), -sin(theta2), 0],
    [sin(theta2), cos(theta2), 0],
    [0, 0, 1]])

T1 = rigidity.AffineTransform(S1, l1)
T2 = rigidity.AffineTransform(S2, l2)

# Define the vertices and edge markings for the graph
verts = [0, 1, 2, 3]
edges = {
    0: [(1, 0, 0), (2, 0, 0), (3, 0, 0)],
    1: [(0, 1, 0), (2, 1, 0), (3, 0, 0)],
    2: [(0, 0, 1), (1, 0, 1), (3, 0, 0)],
    3: [(0, 1, 1), (1, 0, 1), (2, 1, 0)]
}
G = [verts, edges]

# Define the 'base' framework
r1 = np.array([[2, 0, 0]]).transpose()
r2 = np.array([[3, 2, 1]]).transpose()
r3 = np.array([[4, 0, 2]]).transpose()
r4 = np.array([[5, 2, 3]]).transpose()
P = np.column_stack([r1, r2, r3, r4])

# Define the number of group elements to create
n = (24, 2)

# Create the framework
f1 = rigidity.ScrewFramework(G, P, T1, T2)


In [108]:
# Create the rigidity matrix
R = f1.rigidityMatrix()

array([[  1.     ,   2.     ,   1.     ,  -1.     ,  -2.     ,  -1.     ,
          0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ],
       [  2.     ,   0.     ,   2.     ,   0.     ,   0.     ,   0.     ,
         -2.     ,   0.     ,  -2.     ,   0.     ,   0.     ,   0.     ],
       [  3.     ,   2.     ,   3.     ,   0.     ,   0.     ,   0.     ,
          0.     ,   0.     ,   0.     ,  -3.     ,  -2.     ,  -3.     ],
       [  1.59808,   0.23205,  -2.     ,  -1.26795,  -1.     ,   2.     ,
          0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ],
       [  0.     ,   0.     ,   0.     ,   0.4641 ,  -0.     ,   4.     ,
         -0.40192,   0.23205,  -4.     ,   0.     ,   0.     ,   0.     ],
       [  0.     ,   0.     ,   0.     ,   2.     ,   0.     ,   2.     ,
          0.     ,   0.     ,   0.     ,  -2.     ,   0.     ,  -2.     ],
       [  1.95075,  -0.62574,  -8.     ,   0.     ,   0.     ,   0.     ,
         -2.02462,   0.31287,   

In [29]:
%matplotlib widget
f1.draw(n)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## One vertex example

In [32]:
verts = [0]
edges = {0: [(0, 0, 1), (0, 1, 0), (0, 1, 1)]}
G = [verts, edges]

r1 = np.array([1, 0, 0])
P = np.column_stack([r1])

n = (24, 2)
f2 = rigidity.ScrewFramework(G, P, T1, T2)

In [33]:
from sympy import Matrix
R2 = f2.rigidityMatrix()
R2

array([[-2.46233188e-02,  2.77555756e-17,  0.00000000e+00],
       [-2.67949192e-01,  5.55111512e-17,  0.00000000e+00],
       [-4.45708077e-01,  1.11022302e-16,  0.00000000e+00]])

In [34]:
import scipy.linalg
scipy.linalg.null_space(R2)

array([[2.3995217e-16, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00]])

In [35]:
f2.draw(((24,3)))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## Clasical Framework in 3D

In [73]:
verts = [0,1,2,3]
edges = {
    0: [1, 2],
    1: [0, 2, 3],
    2: [0, 1, 3],
    3: [1, 2]
}
G = [verts, edges]

r1 = np.array([0, 0, 0])
r2 = np.array([1, 0, 0])
r3 = np.array([0, 1, 0])
r4 = np.array([0, 0, 1])
P = np.column_stack([r1, r2, r3, r4])

f3 = rigidity.Framework(G, P)

In [74]:
f3.rigidityMatrix()

array([[-1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -1.,  0., -1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0., -1.,  0.,  0.,  0., -1.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  0., -1.,  1.]])

In [75]:
f3.symbolicRigidityMatrix('v')

Matrix([
[v_0,0 - v_1,0, v_0,1 - v_1,1, v_0,2 - v_1,2, -v_0,0 + v_1,0, -v_0,1 + v_1,1, -v_0,2 + v_1,2,              0,              0,              0,              0,              0,              0],
[v_0,0 - v_2,0, v_0,1 - v_2,1, v_0,2 - v_2,2,              0,              0,              0, -v_0,0 + v_2,0, -v_0,1 + v_2,1, -v_0,2 + v_2,2,              0,              0,              0],
[            0,             0,             0,  v_1,0 - v_2,0,  v_1,1 - v_2,1,  v_1,2 - v_2,2, -v_1,0 + v_2,0, -v_1,1 + v_2,1, -v_1,2 + v_2,2,              0,              0,              0],
[            0,             0,             0,  v_1,0 - v_3,0,  v_1,1 - v_3,1,  v_1,2 - v_3,2,              0,              0,              0, -v_1,0 + v_3,0, -v_1,1 + v_3,1, -v_1,2 + v_3,2],
[            0,             0,             0,              0,              0,              0,  v_2,0 - v_3,0,  v_2,1 - v_3,1,  v_2,2 - v_3,2, -v_2,0 + v_3,0, -v_2,1 + v_3,1, -v_2,2 + v_3,2]])

In [76]:
np.linalg.matrix_rank(f3.rigidityMatrix())

5

In [77]:
f3.rigidityMatrix()@f3.nonTrivialFlex()

array([[1.17961196e-16],
       [3.46944695e-17],
       [4.85722573e-17],
       [0.00000000e+00],
       [1.94289029e-16]])

In [50]:
%matplotlib widget
f3.draw()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## Classical Framework in 2D

In [78]:
verts = [0,1,2,3]
edges = {
    0: [1, 2],
    1: [0, 2, 3],
    2: [0, 1, 3],
    3: [1, 2]
}
G = [verts, edges]

r1 = np.array([0, 0])
r2 = np.array([1, 0])
r3 = np.array([0, 1])
r4 = np.array([1, 1])
P = np.column_stack([r1, r2, r3, r4])

f4 = rigidity.Framework(G, P)

In [79]:
f4.rigidityMatrix()

array([[-1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -1., -1.,  1.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0., -1.,  0.,  1.,  0.]])

In [80]:
f4.symbolicRigidityMatrix()

Matrix([
[p_0,0 - p_1,0, p_0,1 - p_1,1, -p_0,0 + p_1,0, -p_0,1 + p_1,1,              0,              0,              0,              0],
[p_0,0 - p_2,0, p_0,1 - p_2,1,              0,              0, -p_0,0 + p_2,0, -p_0,1 + p_2,1,              0,              0],
[            0,             0,  p_1,0 - p_2,0,  p_1,1 - p_2,1, -p_1,0 + p_2,0, -p_1,1 + p_2,1,              0,              0],
[            0,             0,  p_1,0 - p_3,0,  p_1,1 - p_3,1,              0,              0, -p_1,0 + p_3,0, -p_1,1 + p_3,1],
[            0,             0,              0,              0,  p_2,0 - p_3,0,  p_2,1 - p_3,1, -p_2,0 + p_3,0, -p_2,1 + p_3,1]])

In [81]:
f4.rigidityMatrix()@f4.nonTrivialFlex()

array([[-0.18849996,  0.19477564, -0.17979821],
       [-0.19539352,  0.30920077, -0.32806112],
       [-0.26761346,  0.05203557, -0.04853017],
       [-0.09241538,  0.37603219, -0.93760584],
       [-0.00389593,  0.31481855,  0.08590458]])

In [82]:
import utils
P = f4.config
R = f4.rigidityMatrix()
n = len(P.T)
d = f4.dimension

translations = []
for i in range(d):
    translation = np.zeros(d*n)
    translation[i::d] = 1
    translations.append(translation)
trivials = np.column_stack(translations)

rotations = utils.infRotations(d)
for rotMat in rotations:
    infRot = (rotMat@P).ravel('F')
    trivials = np.column_stack([trivials, infRot])

In [105]:
K = scipy.linalg.null_space(R) # Tollerence on orth is wack

In [106]:
f4.draw()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …